### ISSUE TITLE
hello ,i have this problem TypeError: __init__() got an unexpected keyword argument 'r_minimum'

### ISSUE THREAD

**Issue by paulrich1234** [HDI-Project/ATM#117]
Error choosing hyperparameters: datarun=<ID = 1, dataset ID = 1, strategy = uniform__uniform, budget = classifier (100), status: running>
Traceback (most recent call last):
  File "/home/zhaowei/anaconda2/envs/atm_py2.7/lib/python2.7/site-packages/atm-0.1.0-py2.7.egg/atm/worker.py", line 379, in run_classifier
    params = self.tune_hyperparameters(hyperpartition)
  File "/home/zhaowei/anaconda2/envs/atm_py2.7/lib/python2.7/site-packages/atm-0.1.0-py2.7.egg/atm/worker.py", line 189, in tune_hyperparameters
    r_minimum=self.datarun.r_minimum)
TypeError: __init__() got an unexpected keyword argument 'r_minimum'

**Comment by micahjsmith** [comment]
Should be closed by #114. Please update your version of ATM and reopen if you still have this problem.
