### ISSUE TITLE
MySQL setup not working

### ISSUE THREAD

**Issue by schelian** [HDI-Project/ATM#7]
Hi all, any ideas re: the error message below?

```
Collecting mysql-python==1.2.5 (from -r requirements.txt (line 9))
  Downloading MySQL-python-1.2.5.zip (108kB)
    100% |████████████████████████████████| 112kB 9.6MB/s 
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wg4Zpa/mysql-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wg4Zpa/mysql-python/
```

**Comment by kkarrancsu** [comment]
I was able to solve this issue by running:
`sudo apt-get install libmysqlclient-dev`

**Comment by schelian** [comment]
Super! but when I run python atm/worker.py I got nothing but errors for the first few iterations... Will start another issue.
